version: '3'
services:
  logroundrobin:
    image: logroundrobin:latest
    ports:
      - "8080:6000"
    container_name: logroundrobin-container

  logservices-1:
    image: logservice:latest
    ports:
      - "35001:6001"
    container_name: logservices-1

  logservices-2:
    image: logservice:latest
    ports:
      - "35002:6001"
    container_name: logservices-2

  logservices-3:
    image: logservice:latest
    ports:
      - "35003:6001"
    container_name: logservices-3

  mongo-db:
    image: mongo
    container_name: 'mongo-db'
    volumes:
      - 'mongodb:/data/db'
      - 'mongodb_config:/data/configdb'
    ports:
      - '27017:27017'
    command: 'mongod'
volumes:
  mongodb:
  mongodb_config: